baseURL = "https://hyunyoung2.github.io/my-note-for-parallel-programming-at-Udacity/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "my note for parrallel programing  of Udacity"
theme = "docdock"
themesDir = "themes"
publishDir = "docs"

[params]
editURL = "https://github.com/hyunyoung2/my-note-for-parallel-programming-at-Udacity/edit/master/content/"
showVisitedLinks = true # default is false
themeStyle = "original" # "original" or "flex" # default "original"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i>Hyunyoung2's note for parallel programming Github repo"
identifier = "ds"
url = "https://github.com/hyunyoung2/my-note-for-parallel-programming-at-Udacity"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-camera'></i> Showcases"
url = "/showcase"
weight = 11

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30
